### ISSUE TITLE
Request: Array.prototype.smooshDeep

### ISSUE THREAD

**Issue by johntran** [btholt/loldash#1]
I noticed that `smoosh` only goes one level.

https://github.com/btholt/loldash/blob/master/src/smoosh.ts

It would be useful if I could `smoosh` at an infinite depth. I can provide a pull request.

**Comment by OussamaRomdhane** [comment]
Are we calling this smooshDeep or deepSmoosh? That is the question.
But I totally agree this function will be more useful if it went at an infinite depth though we must be aware of circular references in that case.

**Comment by btholt** [comment]
Due to the serious nature of loldash, this should be called `superSmoosh`.

**Comment by Sherman-Chen** [comment]
superSmooth bros!

**Comment by OussamaRomdhane** [comment]
This will be a disruptive technology.
There will always be a pre-superSmoosh era and then the golden age of erudition.

**Comment by btholt** [comment]
Solved with v9002. After much consideration decided to go with `smooosh`.

**Comment by OussamaRomdhane** [comment]
A very serious name for a very serious project.
